### ISSUE TITLE
Brawler special attack unarmed crash

### ISSUE THREAD

**Issue by GadeRicard** [TrashboxBobylev/Rat-King-Adventure#1]
On one of my runs, I was using brawler and was fortunate enough to find two rings of force. I removed my weapon to test the damage of both rings, used special attack, and the game crashed instantly to home. Possibly brawler does not have a special attack set for unarmed, or maybe it was caused by a null reference error.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.5.
